### PR TITLE
Add support for PyPy3 and Python3.2

### PR DESCRIPTION
**Pull request by jamadden**
Almost entirely a mechanical translation of `u` prefix into a call to a new `_u` function.

### CODE REVIEW

**Comment by mgedmin** [comment]
Why do you want to support Python 3.2?

PyPy3, while it claims to only support Python 3.2 currently, actually accepts `u'-prefixed string literals'`, unlike CPython 3.2.

**Comment by jamadden** [comment]
Because @tseaver [asked for it](https://github.com/zopefoundation/zopetoolkit/pull/3#issuecomment-108933356). Since we have PyPy3, which has the Python 3.2 lib as you noted, in most cases it's relatively low-hanging fruit.

**Comment by tseaver** [comment]
Thank you!

@mgedmin, I think the ZTK should support the same set of Python versions, but didn't want to put in the effort to add 3.2 support to the projects which were ported without it.  I have no idea why the PyPy folks decided to add unicode literal support to their "3.2-compatible" release, but that seems kind of bogus (almost as bogus as the CPython team refusing to add it back in time for 3.2).

**Comment by tseaver** [comment]
Released:

- https://pypi.python.org/pypi/zope.i18n/4.0.1

**Pull request merged**
